parameters:
  perlbrew_root: $(Pipeline.Workspace)/perl5/perlbrew
  with_test_prereqs: false

steps:
  - template: ../shared/install-perlbrew.yml
  - task: Cache@2
    displayName: Define perl install
    inputs:
      key: '"v1" | "perl" | "5.30.2" | "with_test_prereqs=${{ parameters.with_test_prereqs }}" | ./deploy/cpanfile'
      path: ${{ parameters.perlbrew_root }}/perls/perl-5.30.2
  - bash: |
      set -e
      set -x
      if [ ! -d "${{ parameters.perlbrew_root }}/perls/perl-5.30.2" ]; then
          "${{ parameters.perlbrew_root }}/bin/perlbrew" install --verbose --notest --noman -j $(nproc) 5.30.2
      fi
    displayName: Perlbrew install Perl 5.30.2
  - template: ../shared/install-cpm.yml
  - bash: |
      set -e
      set -x

      test_flag="--with-test"
      if [ "${{ parameters.with_test_prereqs }}" == "false" ]; then
          test_flag="--without-test"
      fi

      "${{ parameters.perlbrew_root }}/bin/perlbrew" exec --with 5.30.2 \
      "$(Pipeline.Workspace)/bin/cpm" install \
      --global \
      --show-build-log-on-failure \
      --verbose \
      --workers 16 \
      $test_flag \
      --cpanfile ./deploy/cpanfile
    displayName: Install prereqs
