requires 'Git::Helpers';
requires 'Git::Sub';
requires 'JSON::MaybeXS';
requires 'List::AllUtils';
requires 'MetaCPAN::Client';
requires 'Moose';
requires 'Moose::Role';
requires 'MooseX::Getopt::Dashes';
requires 'Path::Tiny';
requires 'Specio::Declare';
requires 'Specio::Library::Builtins';
requires 'Specio::Library::Path::Tiny';
requires 'autodie';
requires 'namespace::autoclean';

# for autodie qw( :all )
requires 'IPC::System::Simple'
